# Content with notebooks

You can also create content with Jupyter Notebooks. This means that you can include
code blocks and their outputs in your book.

## Markdown + notebooks

As it is markdown, you can embed images, HTML, etc into your posts!

![](https://myst-parser.readthedocs.io/en/latest/_static/logo-wide.svg)

You can also $add_{math}$ and

$$
math^{blocks}
$$

or

$$
\begin{aligned}
\mbox{mean} la_{tex} \\ \\
math blocks
\end{aligned}
$$

But make sure you \$Escape \$your \$dollar signs \$you want to keep!

## MyST markdown

MyST markdown works in Jupyter Notebooks as well. For more information about MyST markdown, check
out [the MyST guide in Jupyter Book](https://jupyterbook.org/content/myst.html),
or see [the MyST markdown documentation](https://myst-parser.readthedocs.io/en/latest/).

## Code blocks and outputs

Jupyter Book will also embed your code blocks and output in your book.
For example, here's some sample Matplotlib code:

In [ ]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
plt.ion()

In [ ]:
# Fixing random state for reproducibility
np.random.seed(19680801)

N = 10
data = [np.logspace(0, 1, 100) + np.random.randn(100) + ii for ii in range(N)]
data = np.array(data).T
cmap = plt.cm.coolwarm
rcParams['axes.prop_cycle'] = cycler(color=cmap(np.linspace(0, 1, N)))


from matplotlib.lines import Line2D
custom_lines = [Line2D([0], [0], color=cmap(0.), lw=4),
                Line2D([0], [0], color=cmap(.5), lw=4),
                Line2D([0], [0], color=cmap(1.), lw=4)]

fig, ax = plt.subplots(figsize=(10, 5))
lines = ax.plot(data)
ax.legend(custom_lines, ['Cold', 'Medium', 'Hot']);

There is a lot more that you can do with outputs (such as including interactive outputs)
with your book. For more information about this, see [the Jupyter Book documentation](https://jupyterbook.org)

**Tugas 1**

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset_url="https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/latest/owid-covid-latest.csv"
data=pd.read_csv(dataset_url, index_col=0)

In [3]:
data

,continent,location,last_updated_date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
iso_code,,,,,,,,,,,,,,,,,,,,,
AFG,Asia,Afghanistan,2022-09-20,197608.0,174.0,172.000,7796.0,0.0,0.714,4927.946,...,NaN,NaN,37.746,0.500,64.83,0.511,NaN,NaN,NaN,NaN
OWID_AFR,NaN,Africa,2022-09-20,12346974.0,617.0,710.571,256697.0,8.0,7.571,8867.441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALB,Europe,Albania,2022-09-20,331715.0,114.0,74.857,3589.0,1.0,0.429,116199.194,...,7.100,51.200,NaN,2.890,78.57,0.795,NaN,NaN,NaN,NaN
DZA,Africa,Algeria,2022-09-20,270612.0,0.0,8.714,6879.0,0.0,0.000,6125.497,...,0.700,30.400,83.741,1.900,76.88,0.748,NaN,NaN,NaN,NaN
AND,Europe,Andorra,2022-09-20,46147.0,0.0,4.857,155.0,0.0,0.000,583887.947,...,29.000,37.800,NaN,NaN,83.73,0.868,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WLF,Oceania,Wallis and Futuna,2022-09-20,761.0,0.0,0.000,7.0,0.0,0.000,65451.105,...,NaN,NaN,NaN,NaN,79.94,NaN,NaN,NaN,NaN,NaN
OWID_WRL,NaN,World,2022-09-20,612856738.0,542216.0,476512.286,6529079.0,1707.0,1602.571,77485.633,...,6.434,34.635,60.130,2.705,72.58,0.737,NaN,NaN,NaN,NaN
YEM,Asia,Yemen,2022-09-20,11932.0,0.0,0.000,2155.0,0.0,0.000,361.777,...,7.600,29.200,49.542,0.700,66.12,0.470,NaN,NaN,NaN,NaN
ZMB,Africa,Zambia,2022-09-20,333387.0,0.0,16.143,4017.0,0.0,0.000,17120.365,...,3.100,24.700,13.938,2.000,63.89,0.584,NaN,NaN,NaN,NaN
ZWE,Africa,Zimbabwe,2022-09-20,257156.0,66.0,36.000,5598.0,0.0,0.286,16078.758,...,1.600,30.700,36.791,1.700,61.49,0.571,NaN,NaN,NaN,NaN

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
data[["continent","location","total_cases","total_deaths"]].head(4)

         continent     location  total_cases  total_deaths
iso_code
AFG           Asia  Afghanistan     197608.0        7796.0
OWID_AFR       NaN       Africa   12346974.0      256697.0
ALB         Europe      Albania     331715.0        3589.0
DZA         Africa      Algeria     270612.0        6879.0

In [6]:
data[["continent","location"]].head(4)

         continent     location
iso_code
AFG           Asia  Afghanistan
OWID_AFR       NaN       Africa
ALB         Europe      Albania
DZA         Africa      Algeria

In [7]:
def diss(x,y):
   p=2
   m=0
   for row in["continent","location"]:
      if data[row][x] == data[row][y]:
         m+=1
      return (p-m)/p

In [8]:
print(diss(1,1))
print(diss(1,2))
print(diss(1,3))

1.0
1.0
1.0

**Tugas Diskritisasi**

In [9]:
import pandas as pd
import numpy as np

In [10]:
dataset_url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
data=pd.read_csv(dataset_url)

In [11]:
data[['sepal_length']]

     sepal_length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [12]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [13]:
data['sepal_length']=est.fit_transform(data[['sepal_length']])

In [14]:
data['sepal_length']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    1.0
Name: sepal_length, Length: 150, dtype: float64

In [15]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['sepal_width']=est.fit_transform(data[['sepal_width']])

In [16]:
data['sepal_width']

0      2.0
1      1.0
2      2.0
3      1.0
4      2.0
      ...
145    1.0
146    0.0
147    1.0
148    2.0
149    1.0
Name: sepal_width, Length: 150, dtype: float64

In [17]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['petal_length']=est.fit_transform(data[['petal_length']])

In [18]:
data['petal_length']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: petal_length, Length: 150, dtype: float64

In [19]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['petal_width']=est.fit_transform(data[['petal_width']])

In [20]:
data['petal_width']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    3.0
146    3.0
147    3.0
148    3.0
149    2.0
Name: petal_width, Length: 150, dtype: float64

**Tugas 3**

In [21]:
import pandas as pd
import numpy as np
import math
import operator

In [22]:
dataset_url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
data=pd.read_csv(dataset_url)

In [23]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [24]:
def euclidianDistance(data1, data2, length):
    distance = 0
    for x in range(length):
        distance += np.square(data1[x] - data2[x])
       
    return np.sqrt(distance)
def knn(trainingSet, testInstance, k):
 
    distances = {}
    sort = {}
    length = testInstance.shape[1]
    print(length)
    
    
    # Calculating euclidean distance between each row of training data and test data
    for x in range(len(trainingSet)):
        
       
        dist = euclidianDistance(testInstance, trainingSet.iloc[x], length)
        distances[x] = dist[0]
       
 
    
    # Sorting them on the basis of distance
    sorted_d = sorted(distances.items(), key=operator.itemgetter(1)) #by using it we store indices also
    sorted_d1 = sorted(distances.items())
    print(sorted_d[:5])
    print(sorted_d1[:5])
   
 
    neighbors = []
    
    
    # Extracting top k neighbors
    for x in range(k):
        neighbors.append(sorted_d[x][0])
    counts = {"Iris-setosa":0,"Iris-versicolor":0,"Iris-virginica":0}
    
    
    # Calculating the most freq class in the neighbors
    for x in range(len(neighbors)):
        response = trainingSet.iloc[neighbors[x]][-1]
 
        if response in counts:
            counts[response] += 1
        else:
            counts[response] = 1
  
    print(counts)
    sortedVotes = sorted(counts.items(), key=operator.itemgetter(1), reverse=True)
    print(sortedVotes)
    return(sortedVotes[0][0], neighbors)

In [25]:
testSet = [[1.4, 3.6, 3.4, 1.2]]
test = pd.DataFrame(testSet)
result,neigh = knn(data, test, 4)#here we gave k=4
print("And the flower is:",result)
print("the neighbors are:",neigh)

4
[(57, 3.706750598570128), (8, 3.8065732621348567), (42, 3.817066936798463), (93, 3.8340579025361627), (38, 3.8431757701151272)]
[(0, 4.32434966208793), (1, 4.196427051671457), (2, 4.057092555020159), (3, 3.8858718455450894), (4, 4.237924020083418)]
{'Iris-setosa': 0, 'Iris-versicolor': 0, 'Iris-virginica': 0, 'versicolor': 2, 'setosa': 2}
[('versicolor', 2), ('setosa', 2), ('Iris-setosa', 0), ('Iris-versicolor', 0), ('Iris-virginica', 0)]
And the flower is: versicolor
the neighbors are: [57, 8, 42, 93]

In [26]:
testSet = [[5.0, 3.3, 1.3, 0.2]]
test = pd.DataFrame(testSet)
result,neigh = knn(data, test, 15)
print("And the flower is:",result)
print("the neighbors are:",neigh)

4
[(49, 0.09999999999999987), (35, 0.1414213562373093), (7, 0.22360679774997896), (40, 0.2236067977499791), (39, 0.24494897427831766)]
[(0, 0.24494897427831777), (1, 0.3316624790355397), (2, 0.31622776601683766), (3, 0.48989794855663577), (4, 0.31622776601683816)]
{'Iris-setosa': 0, 'Iris-versicolor': 0, 'Iris-virginica': 0, 'setosa': 15}
[('setosa', 15), ('Iris-setosa', 0), ('Iris-versicolor', 0), ('Iris-virginica', 0)]
And the flower is: setosa
the neighbors are: [49, 35, 7, 40, 39, 0, 28, 17, 9, 34, 37, 2, 4, 1, 27]